### PR TITLE
Rebuild python3801

### PR DESCRIPTION
**Pull request by finagle29**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is a copy of #1, bumping to rerun CI.

### CODE REVIEW

**Comment by finagle29** [comment]
@conda-forge-admin , please rerender

**Comment by finagle29** [comment]
confirming that I've allowed edits from maintainers

@conda-forge-admin , please rerender

**Comment by finagle29** [comment]
@mwcraig @profxj Could you please take a look at this?

**Comment by profxj** [comment]
Looks good to me!

**Comment by profxj** [comment]
merging

**Pull request merged**
